'use client';
import { Provider } from 'react-redux';
import './globals.scss';
import { Inter } from 'next/font/google';
import store from '@/store/store';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Next js home page',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <Provider store={store}>{children}</Provider>
      </body>
    </html>
  );
}
